### ISSUE TITLE
Segmentation fault if resource namespace does not match

### ISSUE THREAD

**Issue by rgladwell** [kubernetes-sigs/kustomize#1230]
Getting segmentation fault on macOS version 10.14.5 for kustomize version 2.1.0 installed via Homebrew formula when trying to build for overlay of config map where namespace does not match.

The base `config-map.yaml` is as follows:

```yml
apiVersion: v1
kind: ConfigMap

metadata:
  name: hello-world-map
  namespace: hello-world-ns

data: {}
```

The overlay `config-map.yml` is as follows:

```yml
apiVersion: v1
kind: ConfigMap

metadata:
  name: hello-world-map

data:
  ingress_host: "example.org"
```

We get the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a95c01]

goroutine 1 [running]:
sigs.k8s.io/kustomize/k8sdeps/transformer/patch.(*transformer).Transform(0xc0003961e0, 0x4eb1c00, 0xc000349080, 0x6400d98, 0x4015a2a)
	/private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/k8sdeps/transformer/patch/transformer.go:51 +0x341
sigs.k8s.io/kustomize/pkg/transformers.(*multiTransformer).transform(0xc00050eb80, 0x4eb1c00, 0xc000349080, 0x1, 0x6)
	/private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/transformers/multitransformer.go:60 +0x79
sigs.k8s.io/kustomize/pkg/transformers.(*multiTransformer).Transform(0xc00050eb80, 0x4eb1c00, 0xc000349080, 0x6, 0xc0004276e0)
	/private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/transformers/multitransformer.go:56 +0x84
sigs.k8s.io/kustomize/pkg/accumulator.(*ResAccumulator).Transform(...)
	/private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/accumulator/resaccumulator.go:133
sigs.k8s.io/kustomize/pkg/target.(*KustTarget).runTransformers(0xc000294440, 0xc0002a72f0, 0x0, 0x0)
	/private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/target/kusttarget.go:322 +0x3fb
sigs.k8s.io/kustomize/pkg/target.(*KustTarget).AccumulateTarget(0xc000294440, 0xc000162200, 0xc000130170, 0xc000347c78)
	/private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/target/kusttarget.go:241 +0x2b6
sigs.k8s.io/kustomize/pkg/target.(*KustTarget).makeCustomizedResMap(0xc000294440, 0x1, 0xc0000cc798, 0x4e60560, 0x57414d8, 0xc00039ebf0)
	/private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/target/kusttarget.go:126 +0x2f
sigs.k8s.io/kustomize/pkg/target.(*KustTarget).MakeCustomizedResMap(...)
	/private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/target/kusttarget.go:117
sigs.k8s.io/kustomize/pkg/commands/build.(*Options).RunBuild(0xc000336480, 0x4e60420, 0xc0000c8000, 0x4e8d860, 0x57414d8, 0x4ea3560, 0x57414d8, 0xc0000cc798, 0x4e60560, 0x57414d8, ...)
	/private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/commands/build/build.go:130 +0x145
sigs.k8s.io/kustomize/pkg/commands/build.NewCmdBuild.func1(0xc0002a4000, 0xc00039ed90, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/commands/build/build.go:80 +0x193
github.com/spf13/cobra.(*Command).execute(0xc0002a4000, 0xc00039ed50, 0x1, 0x1, 0xc0002a4000, 0xc00039ed50)
	/private/tmp/kustomize-20190619-88330-1s3g6c/pkg/mod/github.com/spf13/cobra@v0.0.2/command.go:756 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000139900, 0x4acb8a4, 0xc000347f88, 0xc0000a2058)
	/private/tmp/kustomize-20190619-88330-1s3g6c/pkg/mod/github.com/spf13/cobra@v0.0.2/command.go:846 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/kustomize-20190619-88330-1s3g6c/pkg/mod/github.com/spf13/cobra@v0.0.2/command.go:794
main.main()
	/private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/cmd/kustomize/main.go:13 +0x28
```

If the namespace is copied to the overlay no error occurs.

The expected result should be a meaningful validation message.

**Comment by jbrette** [comment]
@rgladwell This has been addressed by the following pull request: https://github.com/kubernetes-sigs/kustomize/pull/1206
