### ISSUE TITLE
Exception when patching resources that are not in base

### ISSUE THREAD

**Issue by Jonathan34** [kubernetes-sigs/kustomize#1345]
Hi,

I ran a `kustomize build k8s/overlays/development` and I got the message below.

The reason it triggers an exception is that my base kustomization.yaml has 1 resource (A)
and my development overlays defines 3 in patchesStrategicMerge.
It seems like patching a resource that is not defined in base leads to an exception.

It is completely user issue but may be kustomize could handle that case more.. gracefully and point to the error.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a95c01]

goroutine 1 [running]:
sigs.k8s.io/kustomize/k8sdeps/transformer/patch.(*transformer).Transform(0xc000327a40, 0x4eb1c00, 0xc0002d3240, 0x5f9e008, 0x4015a2a)
        /private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/k8sdeps/transformer/patch/transformer.go:51 +0x341
sigs.k8s.io/kustomize/pkg/transformers.(*multiTransformer).transform(0xc0003276c0, 0x4eb1c00, 0xc0002d3240, 0x1, 0x6)
        /private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/transformers/multitransformer.go:60 +0x79
sigs.k8s.io/kustomize/pkg/transformers.(*multiTransformer).Transform(0xc0003276c0, 0x4eb1c00, 0xc0002d3240, 0x6, 0xc000096de0)
        /private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/transformers/multitransformer.go:56 +0x84
sigs.k8s.io/kustomize/pkg/accumulator.(*ResAccumulator).Transform(...)
        /private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/accumulator/resaccumulator.go:133
sigs.k8s.io/kustomize/pkg/target.(*KustTarget).runTransformers(0xc0002244c0, 0xc0003fc270, 0x0, 0x0)
        /private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/target/kusttarget.go:322 +0x3fb
sigs.k8s.io/kustomize/pkg/target.(*KustTarget).AccumulateTarget(0xc0002244c0, 0xc000118800, 0xc0000e00d0, 0xc0002f7c78)
        /private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/target/kusttarget.go:241 +0x2b6
sigs.k8s.io/kustomize/pkg/target.(*KustTarget).makeCustomizedResMap(0xc0002244c0, 0x1, 0xc000010970, 0x4e60560, 0x57414d8, 0xc0002e2ba0)
        /private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/target/kusttarget.go:126 +0x2f
sigs.k8s.io/kustomize/pkg/target.(*KustTarget).MakeCustomizedResMap(...)
        /private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/target/kusttarget.go:117
sigs.k8s.io/kustomize/pkg/commands/build.(*Options).RunBuild(0xc0001f4360, 0x4e60420, 0xc0000b4000, 0x4e8d860, 0x57414d8, 0x4ea3560, 0x57414d8, 0xc000010970, 0x4e60560, 0x57414d8, ...)
        /private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/commands/build/build.go:130 +0x145
sigs.k8s.io/kustomize/pkg/commands/build.NewCmdBuild.func1(0xc0000f5b80, 0xc0002e2d70, 0x1, 0x1, 0x0, 0x0)
        /private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/pkg/commands/build/build.go:80 +0x193
github.com/spf13/cobra.(*Command).execute(0xc0000f5b80, 0xc0002e2d20, 0x1, 0x1, 0xc0000f5b80, 0xc0002e2d20)
        /private/tmp/kustomize-20190619-88330-1s3g6c/pkg/mod/github.com/spf13/cobra@v0.0.2/command.go:756 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f4f00, 0x4acb8a4, 0xc0002f7f88, 0xc0000a0058)
        /private/tmp/kustomize-20190619-88330-1s3g6c/pkg/mod/github.com/spf13/cobra@v0.0.2/command.go:846 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /private/tmp/kustomize-20190619-88330-1s3g6c/pkg/mod/github.com/spf13/cobra@v0.0.2/command.go:794
main.main()
        /private/tmp/kustomize-20190619-88330-1s3g6c/src/kubernetes-sigs/kustomize/cmd/kustomize/main.go:13 +0x28
```

### Expected behavior
no exception

### Actual behavior
exception

Version: {KustomizeVersion:2.1.0 GitCommit:af67c893d87c5fb8200f8a3edac7fdafd61ec0bd BuildDate:2019-06-19T02:13:12+01:00 GoOs:darwin GoArch:amd64}

**Comment by jbrette** [comment]
@Jonathan34  This is a dup of https://github.com/kubernetes-sigs/kustomize/issues/1230
Has been fixed since.
