### ISSUE TITLE
Kustomize crashes when a resource file is not found

### ISSUE THREAD

**Issue by ivan4th** [kubernetes-sigs/kustomize#253]
Commands to reproduce (there must be no `deployment.yaml` file in the current directory):
```
$ cat >kustomization.yaml <<EOF
> resources:
> - deployment.yaml
> secretGenerator:
> - name: secret
>   commands:
>     PASSWORD: "printf pw"
>   type: Opaque
> EOF
$ kustomize build
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/kubernetes-sigs/kustomize/pkg/resmap.MergeWithOverride(0xc42020db70, 0x2, 0x2, 0xc420376ab0, 0x0, 0x0)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/resmap/resmap.go:261 +0x80a
github.com/kubernetes-sigs/kustomize/pkg/app.(*Application).loadCustomizedResMap(0xc4204d6420, 0x72, 0x272, 0xc420108000)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/app/application.go:164 +0x2f9
github.com/kubernetes-sigs/kustomize/pkg/app.(*Application).MakeCustomizedResMap(0xc4204d6420, 0xc4205029c0, 0x1cb4880, 0x2308630)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/app/application.go:84 +0x2b
github.com/kubernetes-sigs/kustomize/pkg/commands.(*buildOptions).RunBuild(0xc4202d5b90, 0x1c96f80, 0xc42000e018, 0x1cb4880, 0x2308630, 0x1bbdefe, 0x4)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/commands/build.go:101 +0x118
github.com/kubernetes-sigs/kustomize/pkg/commands.newCmdBuild.func1(0xc4200e8f00, 0x2308630, 0x0, 0x0, 0x0, 0x0)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/pkg/commands/build.go:55 +0xaf
github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200e8f00, 0x2308630, 0x0, 0x0, 0xc4200e8f00, 0x2308630)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra/command.go:756 +0x468
github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200e8500, 0xc4200e9400, 0xc4200e9680, 0xc42028c000)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200e8500, 0x1c34dc0, 0xc4200a0058)
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
        /Users/ivan4th/work/kubernetes/src/github.com/kubernetes-sigs/kustomize/kustomize.go:30 +0x43
```

**Comment by Liujingfang1** [comment]
In my expectation, if a resource file is not found, Kustomize should exit and show the correct message such as "resource file xxx is not found". Letting Kustomize silently skipping the unfounded resource is not a good idea since it will end up with incomplete output without user's attention. So the fix should be instead of panic, let kustomize exit when a resource file is not found.

**Comment by ivan4th** [comment]
What you described as the expected behaviour is actually what happens after #250.
```
$ cat >kustomization.yaml <<EOF
> resources:
> - deployment.yaml
> secretGenerator:
> - name: secret
>   commands:
>     PASSWORD: "printf pw"
>   type: Opaque
> EOF
$ kustomize build
Error: loadResMapFromBasesAndResources: rawResources failed to read Resources: Load from path deployment.yaml failed: open /Users/ivan4th/kustomize-bug-1/deployment.yaml: no such file or directory
```

The problem was that kustomize tries hard to collect as many errors as possible before giving up to provide user with more comprehensive diagnostics info, and it was crashing on `nil` `ResMap`s while trying to do so. After #253, the errors are not swallowed, it's just the `nil` `ResMap` crash that's fixed.
