### ISSUE TITLE
Regression: Starting with a5631694, kustomize panics when nameReference fieldSpec value is empty

### ISSUE THREAD

**Issue by ephesused** [kubernetes-sigs/kustomize#2808]
If a reference points to a field where the value is empty, kustomize panics. The panic behavior starts with a5631694.

Apologies for the lack of a test case PR.

### Test setup

kustomization.yaml

```yaml
generators:
- generators.yaml

configurations:
- kustomizeconfig.yaml
```

generators.yaml

```yaml
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: secret-example
labels:
  app.kubernetes.io/name: secret-example
literals:
- this_is_a_secret_name=
```

kustomizeconfig.yaml

```yaml
nameReference:
- kind: Secret
  version: v1
  fieldSpecs:
  - path: data/this_is_a_secret_name
    kind: ConfigMap
```

### Expected behavior (9ba04e3f and earlier)

```
$ /project_root/build/kustomize-execs/branch-9ba04e3f/kustomize build .
apiVersion: v1
data:
  this_is_a_secret_name: ""
kind: ConfigMap
metadata:
  name: secret-example-t2h2f5gkdg
$
```

### Actual behavior (a5631694 and later)

```
$ /project_root/build/kustomize-execs/branch-a5631694/kustomize build .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x1002e34]

goroutine 1 [running]:
sigs.k8s.io/kustomize/kyaml/yaml.FieldSetter.Filter(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000320700, 0x0, ...)
        /root/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.4.2/yaml/fns.go:474 +0x7d4
sigs.k8s.io/kustomize/kyaml/yaml.(*RNode).Pipe(0xc000320700, 0xc000098508, 0x1, 0x1, 0xc000320740, 0xc000320740, 0x20a2a20)
        /root/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.4.2/yaml/types.go:464 +0x84
sigs.k8s.io/kustomize/kyaml/yaml.(*RNode).PipeE(0xc000320700, 0xc000098508, 0x1, 0x1, 0x0, 0x0)
        /root/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.4.2/yaml/types.go:475 +0x4d
sigs.k8s.io/kustomize/api/filters/filtersutil.SetScalar.func1(0xc000320700, 0x0, 0xc0006e72a0)
        /project_root/build/repos/kustomize/api/filters/filtersutil/setters.go:13 +0xb8
sigs.k8s.io/kustomize/api/filters/nameref.Filter.setScalar(0x0, 0x0, 0x0, 0x0, 0xc000455d10, 0x9, 0xc000671ac0, 0x1a, 0x0, 0xc00063bc20, ...)
        /project_root/build/repos/kustomize/api/filters/nameref/nameref.go:82 +0x18c
sigs.k8s.io/kustomize/api/filters/nameref.Filter.set(0x0, 0x0, 0x0, 0x0, 0xc000455d10, 0x9, 0xc000671ac0, 0x1a, 0x0, 0xc00063bc20, ...)
        /project_root/build/repos/kustomize/api/filters/nameref/nameref.go:42 +0x2ca
sigs.k8s.io/kustomize/api/filters/fieldspec.Filter.filter(0x0, 0x0, 0x0, 0x0, 0xc000455d10, 0x9, 0xc000671ac0, 0x1a, 0x0, 0xc0004d01e0, ...)
        /project_root/build/repos/kustomize/api/filters/fieldspec/fieldspec.go:52 +0x1c1
sigs.k8s.io/kustomize/api/filters/fieldspec.Filter.field(0x0, 0x0, 0x0, 0x0, 0xc000455d10, 0x9, 0xc000671ac0, 0x1a, 0x0, 0xc0004d01e0, ...)
        /project_root/build/repos/kustomize/api/filters/fieldspec/fieldspec.go:109 +0x4a9
sigs.k8s.io/kustomize/api/filters/fieldspec.Filter.filter(0x0, 0x0, 0x0, 0x0, 0xc000455d10, 0x9, 0xc000671ac0, 0x1a, 0x0, 0xc0004d01e0, ...)
        /project_root/build/repos/kustomize/api/filters/fieldspec/fieldspec.go:58 +0xba
sigs.k8s.io/kustomize/api/filters/fieldspec.Filter.field(0x0, 0x0, 0x0, 0x0, 0xc000455d10, 0x9, 0xc000671ac0, 0x1a, 0x0, 0xc0004d01e0, ...)
        /project_root/build/repos/kustomize/api/filters/fieldspec/fieldspec.go:109 +0x4a9
sigs.k8s.io/kustomize/api/filters/fieldspec.Filter.filter(0x0, 0x0, 0x0, 0x0, 0xc000455d10, 0x9, 0xc000671ac0, 0x1a, 0x0, 0xc0004d01e0, ...)
        /project_root/build/repos/kustomize/api/filters/fieldspec/fieldspec.go:58 +0xba
sigs.k8s.io/kustomize/api/filters/fieldspec.Filter.Filter(0x0, 0x0, 0x0, 0x0, 0xc000455d10, 0x9, 0xc000671ac0, 0x1a, 0x0, 0xc0004d01e0, ...)
        /project_root/build/repos/kustomize/api/filters/fieldspec/fieldspec.go:41 +0x176
sigs.k8s.io/kustomize/kyaml/yaml.(*RNode).Pipe(0xc000320400, 0xc000099270, 0x1, 0x1, 0xc00045fa80, 0xc00045fa80, 0x20c13e0)
        /root/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.4.2/yaml/types.go:464 +0x84
sigs.k8s.io/kustomize/kyaml/yaml.(*RNode).PipeE(0xc000320400, 0xc000099270, 0x1, 0x1, 0xc000700ab0, 0xc0004d0001)
        /root/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.4.2/yaml/types.go:475 +0x4d
sigs.k8s.io/kustomize/api/filters/nameref.Filter.run(0x0, 0x0, 0x0, 0x0, 0xc000455d10, 0x9, 0xc000671ac0, 0x1a, 0x0, 0xc00063bc20, ...)
        /project_root/build/repos/kustomize/api/filters/nameref/nameref.go:29 +0x144
sigs.k8s.io/kustomize/kyaml/yaml.FilterFunc.Filter(0xc0004d0140, 0xc000320400, 0x7fcd7accd108, 0x0, 0x2116aa0)
        /root/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.4.2/yaml/types.go:238 +0x30
sigs.k8s.io/kustomize/kyaml/kio.FilterAll.func1(0xc000010ba8, 0x1, 0x1, 0xc0006e71e0, 0xc000099520, 0x101345d, 0x1fef6a0, 0xc0006e71e0)
        /root/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.4.2/kio/kio.go:121 +0x75
sigs.k8s.io/kustomize/kyaml/kio.FilterFunc.Filter(0xc0006e71e0, 0xc000010ba8, 0x1, 0x1, 0xdeba7f, 0xc000099580, 0x0, 0x0, 0xc0000995f0)
        /root/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.4.2/kio/kio.go:60 +0x44
sigs.k8s.io/kustomize/api/filters/nameref.Filter.Filter(0x0, 0x0, 0x0, 0x0, 0xc000455d10, 0x9, 0xc000671ac0, 0x1a, 0x0, 0xc00063bc20, ...)
        /project_root/build/repos/kustomize/api/filters/nameref/nameref.go:25 +0xb9
sigs.k8s.io/kustomize/kyaml/filtersutil.ApplyToJSON(0x2417a40, 0xc000548e10, 0xc000099848, 0x1, 0x1, 0xc0006e2890, 0x9)
        /root/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.4.2/filtersutil/filtersutil.go:34 +0x19a
sigs.k8s.io/kustomize/api/internal/accumulator.(*nameReferenceTransformer).Transform(0xc0006e7060, 0x2487ee0, 0xc0003973a0, 0xc0003973a0, 0x0)
        /project_root/build/repos/kustomize/api/internal/accumulator/namereferencetransformer.go:87 +0x49e
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
        /project_root/build/repos/kustomize/api/internal/accumulator/resaccumulator.go:138
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).FixBackReferences(0xc000397380, 0xc000397380, 0x0)
        /project_root/build/repos/kustomize/api/internal/accumulator/resaccumulator.go:164 +0xba
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc0000e0730, 0x0, 0x0, 0x247e060, 0x34b17f8)
        /project_root/build/repos/kustomize/api/internal/target/kusttarget.go:128 +0x7b
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
        /project_root/build/repos/kustomize/api/internal/target/kusttarget.go:109
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc000099d20, 0x7ffd66078820, 0x1, 0x0, 0x0, 0x0, 0x0)
        /project_root/build/repos/kustomize/api/krusty/kustomizer.go:78 +0x2b8
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.(*Options).RunBuild(0xc0000a6480, 0x24154a0, 0xc000120008, 0x1, 0x0)
        /project_root/build/repos/kustomize/kustomize/internal/commands/build/build.go:148 +0x86
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.NewCmdBuild.func1(0xc000612580, 0xc00009da90, 0x1, 0x1, 0x0, 0x0)
        /project_root/build/repos/kustomize/kustomize/internal/commands/build/build.go:70 +0xab
github.com/spf13/cobra.(*Command).execute(0xc000612580, 0xc00009da60, 0x1, 0x1, 0xc000612580, 0xc00009da60)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000612000, 0x9, 0x24690c0, 0xc0002fbf80)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /project_root/build/repos/kustomize/kustomize/main.go:23 +0x71
$
```

FYI @Shell32-Natsu

**Comment by Shell32-Natsu** [comment]
Thanks for reporting this. Will take a look at it ASAP.
