### ISSUE TITLE
RoleBinding does not work

### ISSUE THREAD

**Issue by whynowy** [kubernetes-sigs/kustomize#3347]
**Describe the bug**
It panics when there's a `RoleBinding` resource.

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- test-rolebinding.yaml
```

test-rolebinding.yaml

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: ns1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-role
subjects:
  - kind: ServiceAccount
    name: my-sa
    namespace: ns1
```

**Expected output**

A good `RoleBinding` yaml.

**Actual output**

```
panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 1 [running]:
sigs.k8s.io/kustomize/api/resmap.getNamespacesForRoleBinding(0xc00061ff40, 0x19)
	/Users/xxxxx/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/resmap/reswrangler.go:417 +0x352
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).SubsetThatCouldBeReferencedByResource(0xc0003c56a0, 0xc00061ff40, 0xb, 0xc0002b7601)
	/Users/xxxxx/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/resmap/reswrangler.go:384 +0xdb
sigs.k8s.io/kustomize/api/internal/accumulator.(*nameReferenceTransformer).Transform(0xc00047b0e0, 0x55593a0, 0xc0003c56a0, 0xc0003c56a0, 0x0)
	/Users/xxxxx/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/accumulator/namereferencetransformer.go:85 +0x531
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
	/Users/xxxxx/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/accumulator/resaccumulator.go:138
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).FixBackReferences(0xc0003c5680, 0xc0003c5680, 0x0)
	/Users/xxxxx/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/accumulator/resaccumulator.go:164 +0xbe
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc000534600, 0x0, 0x0, 0x5551440, 0x5fb6700)
	/Users/xxxxx/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/target/kusttarget.go:125 +0x7d
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	/Users/xxxxx/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/target/kusttarget.go:106
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc000149d20, 0x7ffeefbff990, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/xxxxx/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/krusty/kustomizer.go:77 +0x29b
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.(*Options).RunBuild(0xc0004c8150, 0x54fc2e0, 0xc000010018, 0x1, 0x0)
	/private/tmp/kustomize-20201211-78190-118b0q5/kustomize/internal/commands/build/build.go:148 +0xb5
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.NewCmdBuild.func1(0xc000293b80, 0xc00052bd70, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/kustomize-20201211-78190-118b0q5/kustomize/internal/commands/build/build.go:70 +0xad
github.com/spf13/cobra.(*Command).execute(0xc000293b80, 0xc00052bd40, 0x1, 0x1, 0xc000293b80, 0xc00052bd40)
	/Users/xxxxx/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000293600, 0x0, 0xffffffff, 0xc00018e058)
	/Users/xxxxx/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/xxxxx/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/private/tmp/kustomize-20201211-78190-118b0q5/kustomize/main.go:19 +0x2a
```

**Kustomize version**

```
{Version:kustomize/v3.9.0 GitCommit:826b5d9792fb67c4d8f8cd59747698ebf0b22720 BuildDate:2020-12-11T12:12:22-08:00 GoOs:darwin GoArch:amd64}
```

**Platform**

`macOS`

**Additional context**

**Comment by Shell32-Natsu** [comment]
https://github.com/kubernetes-sigs/kustomize/issues/3340#issuecomment-742843704
