### ISSUE TITLE
Getting Panic when building

### ISSUE THREAD

**Issue by TechnicalMercenary** [kubernetes-sigs/kustomize#3355]
```
panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 1 [running]:
sigs.k8s.io/kustomize/api/resmap.getNamespacesForRoleBinding(0xc000392960, 0x19)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/resmap/reswrangler.go:417 +0x352
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).SubsetThatCouldBeReferencedByResource(0xc00035e440, 0xc000392960, 0xb, 0xc000e2b801)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/resmap/reswrangler.go:384 +0xdb
sigs.k8s.io/kustomize/api/internal/accumulator.(*nameReferenceTransformer).Transform(0xc000f38e20, 0x555a040, 0xc00035e440, 0xc00035e440, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/accumulator/namereferencetransformer.go:85 +0x531
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/accumulator/resaccumulator.go:138
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).FixBackReferences(0xc00035e420, 0xc00035e420, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/accumulator/resaccumulator.go:164 +0xbe
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc0004b7b40, 0x0, 0x0, 0x55520e0, 0x5fb6700)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/target/kusttarget.go:125 +0x7d
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/target/kusttarget.go:106
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc0005cfd20, 0x7ffeefbff588, 0x53, 0x0, 0x0, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/krusty/kustomizer.go:77 +0x29b
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.(*Options).RunBuild(0xc0008a4bd0, 0x54fcf80, 0xc000010018, 0x1, 0x0)
	/private/tmp/kustomize-20201210-84904-1cs0sa6/kustomize/internal/commands/build/build.go:148 +0xb5
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.NewCmdBuild.func1(0xc000223b80, 0xc0004c5d90, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/kustomize-20201210-84904-1cs0sa6/kustomize/internal/commands/build/build.go:70 +0xad
github.com/spf13/cobra.(*Command).execute(0xc000223b80, 0xc0004c5d60, 0x1, 0x1, 0xc000223b80, 0xc0004c5d60)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000223600, 0x0, 0xffffffff, 0xc0000a8058)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/private/tmp/kustomize-20201210-84904-1cs0sa6/kustomize/main.go:19 +0x2a
```

**Files that can reproduce the issue**

**Expected output**

**Actual output**

{Version:kustomize/v3.9.0 GitCommit:826b5d9792fb67c4d8f8cd59747698ebf0b22720 BuildDate:2020-12-10T21:52:58+00:00 GoOs:darwin GoArch:amd64}

**Platform**

MacOS

**Additional context**

I'm working on a minimal version

**Comment by Shell32-Natsu** [comment]
Duplicate with #3340
