### ISSUE TITLE
`kustomize build` panics if the comment contains multibyte characters

### ISSUE THREAD

**Issue by johejo** [kubernetes-sigs/kustomize#3358]
**Describe the bug**

kustomize crashed when using Japanese kanji and hiragana in yaml comments.
It does not occur in v3.8.8.
It seems to be a regression.

**Files that can reproduce the issue**

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml
```

resources.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  template:
    spec:
      containers:
        - name: nginx # あ
          image: nginx
```

**Expected output**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  template:
    spec:
      containers:
      - image: nginx
        name: nginx
```

**Actual output**

```
panic: runtime error: index out of range [4] with length 4 [recovered]
        panic: runtime error: index out of range [4] with length 4

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc000527290)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/yaml.go:276 +0x85
panic(0x1d22220, 0xc0004f80c0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.15.5/libexec/src/runtime/panic.go:969 +0x1b9
gopkg.in/yaml%2ev3.write(0xc0006ac380, 0xc00043e318, 0x4, 0x8, 0xc0005234d0, 0xcf4601)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:90 +0x245
gopkg.in/yaml%2ev3.yaml_emitter_write_comment(0xc0006ac380, 0xc00043e318, 0x4, 0x8, 0x1)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:1978 +0x1ae
gopkg.in/yaml%2ev3.yaml_emitter_process_line_comment(0xc0006ac380, 0xc000499980)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:1128 +0x6a
gopkg.in/yaml%2ev3.yaml_emitter_emit_block_mapping_value(0xc0006ac380, 0xc000499980, 0x1, 0x1)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:817 +0xec
gopkg.in/yaml%2ev3.yaml_emitter_state_machine(0xc0006ac380, 0xc000499980, 0x1)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:303 +0x445
gopkg.in/yaml%2ev3.yaml_emitter_emit(0xc0006ac380, 0xc0006ac5c0, 0xc00043e328)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:153 +0x14f
gopkg.in/yaml%2ev3.(*encoder).emit(0xc0006ac380)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:81 +0x39
gopkg.in/yaml%2ev3.(*encoder).emitScalar(0xc0006ac380, 0xc0001f7f90, 0x5, 0x0, 0x0, 0x0, 0x0, 0xc000592c02, 0x2a798c0, 0x0, ...)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:417 +0x31a
gopkg.in/yaml%2ev3.(*encoder).node(0xc0006ac380, 0xc0006490e0, 0x0, 0x0)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:559 +0x136f
gopkg.in/yaml%2ev3.(*encoder).node(0xc0006ac380, 0xc000648f00, 0x0, 0x0)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:508 +0xb25
gopkg.in/yaml%2ev3.(*encoder).node(0xc0006ac380, 0xc000648e60, 0x0, 0x0)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:478 +0x5fc
gopkg.in/yaml%2ev3.(*encoder).node(0xc0006ac380, 0xc000648d20, 0x0, 0x0)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc0006ac380, 0xc000648be0, 0x0, 0x0)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc0006ac380, 0xc000648aa0, 0x0, 0x0)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc0006ac380, 0xc000648320, 0x0, 0x0)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc0006ac380, 0xc0006481e0, 0x0, 0x0)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:463 +0x245
gopkg.in/yaml%2ev3.(*encoder).nodev(0xc0006ac380, 0x1cb53c0, 0xc0006481e0, 0x16)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:421 +0x79
gopkg.in/yaml%2ev3.(*encoder).marshalDoc(0xc0006ac380, 0x0, 0x0, 0x1cb53c0, 0xc0006481e0, 0x16)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:101 +0x23a
gopkg.in/yaml%2ev3.(*Encoder).Encode(0xc00061c028, 0x1cb53c0, 0xc0006481e0, 0x0, 0x0)
        /home/heijo/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/yaml.go:251 +0xea
sigs.k8s.io/kustomize/kyaml/yaml.String(0xc0006481e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/heijo/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.3/yaml/types.go:202 +0x1b3
sigs.k8s.io/kustomize/kyaml/yaml.(*RNode).String(...)
        /home/heijo/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.3/yaml/rnode.go:435
sigs.k8s.io/kustomize/kyaml/yaml.(*RNode).MarshalJSON(0xc0006ae3c0, 0x2, 0xc0001f7e00, 0x8, 0xc0001f7d68, 0x7)
        /home/heijo/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.3/yaml/rnode.go:641 +0x37a
sigs.k8s.io/kustomize/api/internal/wrappy.(*WNode).MarshalJSON(0xc00058e358, 0x203000, 0x203000, 0x203000, 0xc0005275b0, 0xad685f)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/api/internal/wrappy/wnode.go:162 +0x2e
sigs.k8s.io/kustomize/api/resource.(*Resource).MarshalJSON(0xc000649220, 0x1fc8e00, 0xad9db0, 0xc000870700, 0x70, 0x68)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/api/resource/resource.go:82 +0x33
sigs.k8s.io/kustomize/kyaml/filtersutil.GetRNode(0x1fc8e00, 0xc000649220, 0xc000649220, 0x1fc8e00, 0xc000649220)
        /home/heijo/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.3/filtersutil/filtersutil.go:60 +0x35
sigs.k8s.io/kustomize/kyaml/filtersutil.ApplyToJSON(0x1fcac80, 0xc000870700, 0xc0005276e0, 0x1, 0x1, 0xc000592b60, 0x0)
        /home/heijo/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.3/filtersutil/filtersutil.go:26 +0xa9
sigs.k8s.io/kustomize/api/builtins.(*PrefixSuffixTransformerPlugin).Transform(0xc0006514c0, 0x20259a0, 0xc000475240, 0x0, 0x0)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/api/builtins/PrefixSuffixTransformer.go:73 +0x4a5
sigs.k8s.io/kustomize/api/internal/target.(*multiTransformer).transform(0xc00070a760, 0x20259a0, 0xc000475240, 0xc00085a001, 0x4)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/api/internal/target/multitransformer.go:40 +0x79
sigs.k8s.io/kustomize/api/internal/target.(*multiTransformer).Transform(0xc00070a760, 0x20259a0, 0xc000475240, 0xc00085a000, 0x4)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/api/internal/target/multitransformer.go:35 +0x85
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/api/internal/accumulator/resaccumulator.go:138
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).runTransformers(0xc0006ae040, 0xc000475220, 0x0, 0x0)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/api/internal/target/kusttarget.go:269 +0x24a
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc0006ae040, 0xc000475220, 0x0, 0x4, 0x1)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/api/internal/target/kusttarget.go:194 +0x28d
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0xc0006ae040, 0x40, 0xc0006ae300, 0x1)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/api/internal/target/kusttarget.go:155 +0xce
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc0006ae040, 0x0, 0x0, 0x201da40, 0x2a798c0)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/api/internal/target/kusttarget.go:110 +0x2f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/api/internal/target/kusttarget.go:106
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc000527d20, 0x7ffefba500d4, 0x51, 0x0, 0x0, 0x0, 0x0)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/api/krusty/kustomizer.go:77 +0x29b
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.(*Options).RunBuild(0xc000858bd0, 0x1fc8ba0, 0xc000010018, 0x1, 0x0)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/kustomize/internal/commands/build/build.go:148 +0xb5
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.NewCmdBuild.func1(0xc00030db80, 0xc000220010, 0x1, 0x1, 0x0, 0x0)
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/kustomize/internal/commands/build/build.go:70 +0xad
github.com/spf13/cobra.(*Command).execute(0xc00030db80, 0xc0001a0210, 0x1, 0x1, 0xc00030db80, 0xc0001a0210)
        /home/heijo/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00030d600, 0x0, 0xffffffff, 0xc000048118)
        /home/heijo/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/heijo/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/heijo/ghq/github.com/kubernetes-sigs/kustomize/kustomize/main.go:19 +0x2a
exit status 2

```

**Kustomize version**

- 67e445c1
- kustomize/v3.9.0

**Platform**

Linux

**Additional context**

**Comment by Shell32-Natsu** [comment]
@monopole I believe this is the issue in kyaml or go-yaml v3.

**Comment by ichizero** [comment]
The above case seems to be resolved in Kustomize v3.9.2.
However, the error still occurs when the patch file contains multibyte character comments.

kustomization.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml
patchesStrategicMerge:
  - patch.yaml
```

resources.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: nginx
```

patch.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: my-nginx # あ
```

Output

<details>

```bash
panic: runtime error: index out of range [4] with length 3 [recovered]
	panic: runtime error: index out of range [4] with length 3

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc00002b290)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/yaml.go:276 +0x85
panic(0x525d8e0, 0xc002754ce0)
	/usr/local/Cellar/go/1.15.7/libexec/src/runtime/panic.go:969 +0x1b9
gopkg.in/yaml%2ev3.write(0xc002e86a80, 0xc0025d5d48, 0x3, 0x8, 0xc0000274d0, 0x443f001)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:90 +0x245
gopkg.in/yaml%2ev3.yaml_emitter_write_comment(0xc002e86a80, 0xc0025d5d48, 0x3, 0x8, 0x1)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:1978 +0x1ae
gopkg.in/yaml%2ev3.yaml_emitter_process_line_comment(0xc002e86a80, 0xc0001665f0)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:1128 +0x6a
gopkg.in/yaml%2ev3.yaml_emitter_emit_block_mapping_value(0xc002e86a80, 0xc0001665f0, 0x1, 0x4010601)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:817 +0xec
gopkg.in/yaml%2ev3.yaml_emitter_state_machine(0xc002e86a80, 0xc0001665f0, 0x203001)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:303 +0x445
gopkg.in/yaml%2ev3.yaml_emitter_emit(0xc002e86a80, 0xc002e86cc0, 0xc0025d5d50)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/emitterc.go:153 +0x14f
gopkg.in/yaml%2ev3.(*encoder).emit(0xc002e86a80)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:81 +0x39
gopkg.in/yaml%2ev3.(*encoder).emitScalar(0xc002e86a80, 0xc0001e36b0, 0x8, 0x0, 0x0, 0x0, 0x0, 0xc001f6b302, 0x5fba780, 0x0, ...)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:417 +0x31a
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e86a80, 0xc00029f680, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:559 +0x136f
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e86a80, 0xc00077e0a0, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e86a80, 0xc00077e000, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:478 +0x5fc
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e86a80, 0xc000621e00, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e86a80, 0xc000621b80, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e86a80, 0xc000621900, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e86a80, 0xc000620140, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:512 +0xa6f
gopkg.in/yaml%2ev3.(*encoder).node(0xc002e86a80, 0xc0006200a0, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:463 +0x245
gopkg.in/yaml%2ev3.(*encoder).nodev(0xc002e86a80, 0x51f0d20, 0xc0006200a0, 0x16)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:421 +0x79
gopkg.in/yaml%2ev3.(*encoder).marshalDoc(0xc002e86a80, 0x0, 0x0, 0x51f0d20, 0xc0006200a0, 0x16)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/encode.go:101 +0x23a
gopkg.in/yaml%2ev3.(*Encoder).Encode(0xc002cca0e8, 0x51f0d20, 0xc0006200a0, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/yaml.go:251 +0xea
sigs.k8s.io/kustomize/kyaml/yaml.String(0xc0006200a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.6/yaml/types.go:215 +0x1b3
sigs.k8s.io/kustomize/kyaml/yaml.(*RNode).String(...)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.6/yaml/rnode.go:468
sigs.k8s.io/kustomize/kyaml/yaml.(*RNode).MarshalJSON(0xc00015aec0, 0x0, 0x0, 0x0, 0x0, 0xc0009a6200)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.6/yaml/rnode.go:674 +0x37a
sigs.k8s.io/kustomize/api/internal/wrappy.(*WNode).MarshalJSON(0xc002cca0e0, 0x0, 0x0, 0x5350053, 0x21, 0x0)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/wrappy/wnode.go:219 +0x2e
sigs.k8s.io/kustomize/api/resource.(*Resource).MarshalJSON(0xc000896140, 0x0, 0x0, 0xc0009a6200, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/resource/resource.go:93 +0x33
sigs.k8s.io/kustomize/kyaml/filtersutil.GetRNode(0x5505d80, 0xc000896140, 0xc002d3a5a0, 0xc00002b600, 0x44d32b9)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.10.6/filtersutil/filtersutil.go:60 +0x35
sigs.k8s.io/kustomize/api/resource.(*Resource).ApplySmPatch(0xc0001b2320, 0xc000896140, 0x5, 0xc00036ef01)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/resource/resource.go:491 +0x3b
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).ApplySmPatch(0xc0004db8a0, 0xc002cca0c0, 0xc0000a4a00, 0xc002cca0c0, 0x2)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/resmap/reswrangler.go:593 +0x32a
sigs.k8s.io/kustomize/api/builtins.(*PatchStrategicMergeTransformerPlugin).Transform(0xc00034aa80, 0x55631e0, 0xc0004db8a0, 0xc00045b200, 0x0)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/builtins/PatchStrategicMergeTransformer.go:77 +0x176
sigs.k8s.io/kustomize/api/internal/target.(*multiTransformer).transform(0xc0003ce080, 0x55631e0, 0xc0004db8a0, 0xc000896a01, 0x5)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/multitransformer.go:40 +0x79
sigs.k8s.io/kustomize/api/internal/target.(*multiTransformer).Transform(0xc0003ce080, 0x55631e0, 0xc0004db8a0, 0xc000896af0, 0x5)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/multitransformer.go:35 +0x85
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/accumulator/resaccumulator.go:141
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).runTransformers(0xc00033d040, 0xc0004db880, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/kusttarget.go:269 +0x24a
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc00033d040, 0xc0004db880, 0x0, 0x4, 0x1)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/kusttarget.go:194 +0x28d
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0xc00033d040, 0x40, 0xc00033d9c0, 0xc0004da601)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/kusttarget.go:155 +0xce
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc00033d040, 0x0, 0x0, 0x555adc0, 0x5fba780)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/kusttarget.go:110 +0x2f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/internal/target/kusttarget.go:106
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc00002bd20, 0x7ffeefbff79b, 0x2, 0x0, 0x0, 0x0, 0x0)
	/Users/xxx/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.2/krusty/kustomizer.go:77 +0x29b
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.(*Options).RunBuild(0xc000777f80, 0x5505b20, 0xc00018a008, 0x1, 0x0)
	/Users/xxx/ghq/github.com/kubernetes-sigs/kustomize/kustomize/internal/commands/build/build.go:148 +0xb5
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.NewCmdBuild.func1(0xc0001de000, 0xc0002c2820, 0x1, 0x1, 0x0, 0x0)
	/Users/xxx/ghq/github.com/kubernetes-sigs/kustomize/kustomize/internal/commands/build/build.go:70 +0xad
github.com/spf13/cobra.(*Command).execute(0xc0001de000, 0xc0002c27f0, 0x1, 0x1, 0xc0001de000, 0xc0002c27f0)
	/Users/xxx/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00037d8c0, 0x0, 0xffffffff, 0xc0000b2058)
	/Users/xxx/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/xxx/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/xxx/ghq/github.com/kubernetes-sigs/kustomize/kustomize/main.go:19 +0x2a
```

</details>

Expected output (by Kustomize v3.8.9)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  template:
    spec:
      containers:
      - image: my-nginx
        name: nginx
```

**Comment by natasha41575** [comment]
Adding a note that when multibyte characters are used in data, there is no panic (see #3679). In order to not lose data in those scenarios, the solution moving forward would be to remove such characters only from comments

**Comment by natasha41575** [comment]
Update: we're planning to bump go-yaml in kustomize soon. The issue should be resolved after that.
