### ISSUE TITLE
make test-unit-kustomize-api fails on macOS

### ISSUE THREAD

**Issue by sylr** [kubernetes-sigs/kustomize#3890]
**Describe the bug**

```shell
$ make test-unit-kustomize-api
...
--- FAIL: TestHelmChartInflationGeneratorOld (0.78s)
panic: something strange about th.ldr.Root() = /private/var/folders/kg/_2xf2wmd3bd4k50vgy8hrww89x8bnr/T/kust-testing-792527537 [recovered]
	panic: something strange about th.ldr.Root() = /private/var/folders/kg/_2xf2wmd3bd4k50vgy8hrww89x8bnr/T/kust-testing-792527537

goroutine 196 [running]:
testing.tRunner.func1.2(0x459b5e0, 0xc000350610)
	/usr/local/Cellar/go/1.16.3/libexec/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc0006e2f00)
	/usr/local/Cellar/go/1.16.3/libexec/src/testing/testing.go:1146 +0x4b6
panic(0x459b5e0, 0xc000350610)
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/panic.go:965 +0x1b9
sigs.k8s.io/kustomize/api/testutils/kusttest.(*HarnessEnhanced).Reset(0xc0007520f0)
	/Users/s.rabot/go/src/sigs.k8s.io/kustomize/api/testutils/kusttest/harnessenhanced.go:107 +0x187
sigs.k8s.io/kustomize/api/krusty_test.TestHelmChartInflationGeneratorOld(0xc0006e2f00)
	/Users/s.rabot/go/src/sigs.k8s.io/kustomize/api/krusty/helmchartinflationgenerator_test.go:64 +0x2eb
testing.tRunner(0xc0006e2f00, 0x46b8400)
	/usr/local/Cellar/go/1.16.3/libexec/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/Cellar/go/1.16.3/libexec/src/testing/testing.go:1238 +0x2b3
```

**Kustomize version**

master

**Platform**

macOS

**Additional context**

**Comment by monopole** [comment]
Fixed by https://github.com/kubernetes-sigs/kustomize/pull/3889
