### ISSUE TITLE
Private git repo in resources doesn't seem to work (index out of range [0] with length 0)

### ISSUE THREAD

**Issue by jackivanov** [kubernetes-sigs/kustomize#4079]
**Describe the bug**

I'm trying to use a private git repo as the base source for resources. I can clone the repo locally, but not with kustomize.

> Directory specification can be relative, absolute, or part of a URL. URL specifications should follow the hashicorp URL format. The directory must contain a kustomization.yaml file.

**Files that can reproduce the issue**

Example:

```
% cat ./dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
resources:
  - ssh://git@domain.com:2222/project/repo.git
```

**Actual output**

```
% kustomize build ./dev
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
sigs.k8s.io/kustomize/api/internal/git.parseGitUrl(0xc000343c80, 0x34, 0x4bfd660, 0x0, 0x5f225c0, 0x18, 0x18, 0x4e9da68, 0x18, 0xc00013d2c0, ...)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/git/repospec.go:128 +0x805
sigs.k8s.io/kustomize/api/internal/git.NewRepoSpecFromUrl(0xc000343c80, 0x34, 0xc00029f450, 0x46093bd, 0x4838c00)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/git/repospec.go:89 +0x76
sigs.k8s.io/kustomize/api/loader.(*fileLoader).New(0xc00036e0f0, 0xc000343c80, 0x34, 0x34, 0x4838cc0, 0xc00013d2c0, 0x203000)
	sigs.k8s.io/kustomize/api@v0.8.11/loader/fileloader.go:174 +0x5f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateResources(0xc00032b000, 0xc00039a180, 0xc00032b480, 0x1, 0x4, 0x4bfd660, 0x0, 0xc00029f578)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:339 +0x147
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc00032b000, 0xc00039a180, 0xc00029f610, 0x4449453, 0x0)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:163 +0x74
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0xc00032b000, 0x0, 0xffffffffffffffff, 0x0)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:156 +0xce
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc00032b000, 0x0, 0x0, 0x0, 0x1)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:111 +0x2f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:107
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc00029fd60, 0x484ea60, 0x4c2c0d8, 0x7ffeefbff828, 0x5, 0x0, 0x0, 0x0, 0x0)
	sigs.k8s.io/kustomize/api@v0.8.11/krusty/kustomizer.go:88 +0x3dd
sigs.k8s.io/kustomize/kustomize/v4/commands/build.NewCmdBuild.func1(0xc00034e580, 0xc0003604a0, 0x1, 0x1, 0x0, 0x0)
	sigs.k8s.io/kustomize/kustomize/v4/commands/build/build.go:80 +0x1c9
github.com/spf13/cobra.(*Command).execute(0xc00034e580, 0xc000360470, 0x1, 0x1, 0xc00034e580, 0xc000360470)
	github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00034e000, 0x0, 0xffffffff, 0xc00010e058)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	sigs.k8s.io/kustomize/kustomize/v4/main.go:14 +0x2a
```

**Kustomize version**

```
% kustomize version
{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-07-01T01:00:35+01:00 GoOs:darwin GoArch:amd64}
```

**Platform**

macOS

**Additional context**

I'm able to clone the repo

```
% git clone ssh://git@domain.com:2222/project/repo.git
Cloning into 'repo'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (6/6), done.
```

I tried different URL formats that go-getter supports, none of them worked

**Comment by natasha41575** [comment]
This was fixed by https://github.com/kubernetes-sigs/kustomize/pull/4039 and should be available in the next release.
