### ISSUE TITLE
CRD panic

### ISSUE THREAD

**Issue by lswith** [kubernetes-sigs/kustomize#479]
I recieved a panic from kustomize when using a crd.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x161b00d]

goroutine 1 [running]:
sigs.k8s.io/kustomize/pkg/transformers/config.(*TransformerConfig).Merge(0xc00038ea20, 0x0, 0x1)
        /Users/lswith/go/src/sigs.k8s.io/kustomize/pkg/transformers/config/transformerconfig.go:68 +0x5d
sigs.k8s.io/kustomize/pkg/target.(*KustTarget).loadCustomizedResMap(0xc0002ae0a0, 0x1c3, 0x3c3, 0xc00013a000)
        /Users/lswith/go/src/sigs.k8s.io/kustomize/pkg/target/kusttarget.go:136 +0x11c
sigs.k8s.io/kustomize/pkg/target.(*KustTarget).MakeCustomizedResMap(0xc0002ae0a0, 0xc0003618e0, 0x1fe1420, 0x2a05108)
        /Users/lswith/go/src/sigs.k8s.io/kustomize/pkg/target/kusttarget.go:93 +0x2b
sigs.k8s.io/kustomize/pkg/commands/build.(*buildOptions).RunBuild(0xc000323580, 0x1fbe720, 0xc0000cc008, 0x1fe1420, 0x2a05108, 0xc0000e2700, 0x1fc3340, 0x2a05108, 0x0, 0x0)
        /Users/lswith/go/src/sigs.k8s.io/kustomize/pkg/commands/build/build.go:141 +0x19f
sigs.k8s.io/kustomize/pkg/commands/build.NewCmdBuild.func1(0xc000406280, 0xc000226cb0, 0x1, 0x1, 0x0, 0x0)
        /Users/lswith/go/src/sigs.k8s.io/kustomize/pkg/commands/build/build.go:78 +0x155
sigs.k8s.io/kustomize/vendor/github.com/spf13/cobra.(*Command).execute(0xc000406280, 0xc000226c70, 0x1, 0x1, 0xc000406280, 0xc000226c70)
        /Users/lswith/go/src/sigs.k8s.io/kustomize/vendor/github.com/spf13/cobra/command.go:756 +0x473
sigs.k8s.io/kustomize/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000406000, 0xc000406500, 0xc00040a500, 0xc00040aa00)
        /Users/lswith/go/src/sigs.k8s.io/kustomize/vendor/github.com/spf13/cobra/command.go:846 +0x2fd
sigs.k8s.io/kustomize/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000406000, 0xc000406000, 0x1bcced8)
        /Users/lswith/go/src/sigs.k8s.io/kustomize/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
        /Users/lswith/go/src/sigs.k8s.io/kustomize/kustomize.go:30 +0x171
```

This is due to not managing the possible chance of `nil` being returned from LoadCRDs.

**Comment by Liujingfang1** [comment]
Is the panic for the crd example in #480

**Comment by lswith** [comment]
Yes it is.

**Comment by Liujingfang1** [comment]
We recommend using a customized transformer configurations for CRDs, which is documented in #498.
