### ISSUE TITLE
kustomize is raising a runtime error when hitting `edit fix --vars` command

### ISSUE THREAD

**Issue by amine-khemissi** [kubernetes-sigs/kustomize#5299]
### What happened?

to remove deprecated keywords, I am launching `kusomize edit fix --vars` on a crd dir

The issue is coming from [this function](https://github.com/kubernetes-sigs/kustomize/blob/f8391994b4dc1558fa25596d41311fde07f96e46/kustomize/commands/edit/fix/convert.go#L287)

We assume that the patch.Target is not nil... in this case it is.

### What did you expect to happen?

to have a valid output, or to raise an error if the grammar of the file is incorrect.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
```

```yaml
# resources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-object
data:
  placeholder: data
```

### Expected output

```yaml

```

### Actual output

```bash
kustomize edit fix --vars 
# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe773b4]

goroutine 1 [running]:
sigs.k8s.io/kustomize/api/types.(*Selector).Copy(...)
        /home/amine/dev/kustomize/api/types/selector.go:32
sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix.writePatchTargets({{0xc0027f1520, 0x1d}, {0x0, 0x0}, 0x0, 0x0}, 0xd24635?, {0x0, 0x0, 0x0}, ...)
        /home/amine/dev/kustomize/kustomize/commands/edit/fix/convert.go:288 +0x74
sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix.constructTargets({0xc000041d10, 0x21}, 0x1160220?, {0x0?, 0x0, 0x0}, {0x0, 0x0, 0x0})
        /home/amine/dev/kustomize/kustomize/commands/edit/fix/convert.go:245 +0x38f
sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix.addTargets(0xc0014f3b88, {0xc0025b2b28, 0x15}, {0xc0002a7f00?, 0xf, 0x2?}, {0x1160220, 0x16e8cd0})
        /home/amine/dev/kustomize/kustomize/commands/edit/fix/convert.go:120 +0x195
sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix.ConvertVarsToReplacements({0x1160220, 0x16e8cd0}, 0xc000213080)
        /home/amine/dev/kustomize/kustomize/commands/edit/fix/convert.go:36 +0x396
sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix.RunFix({0x1160220, 0x16e8cd0}, {0x11565e0, 0xc000014018})
        /home/amine/dev/kustomize/kustomize/commands/edit/fix/fix.go:63 +0x139
sigs.k8s.io/kustomize/kustomize/v5/commands/edit/fix.NewCmdFix.func1(0xc00028af00?, {0x100a1cb?, 0x1?, 0x1?})
        /home/amine/dev/kustomize/kustomize/commands/edit/fix/fix.go:35 +0x29
github.com/spf13/cobra.(*Command).execute(0xc00028af00, {0xc00021bbc0, 0x1, 0x1})
        /home/amine/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000250000)
        /home/amine/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/amine/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/amine/dev/kustomize/kustomize/main.go:14 +0x1e

```

### Kustomize version

v5.1.1

### Operating system

Linux

**Comment by annasong20** [comment]
Can no longer reproduce this error. Probably fixed by #5211.
/close 
as completed
