### ISSUE TITLE
panic: kustomize flag redefined: log_dir

### ISSUE THREAD

**Issue by jcassee** [kubernetes-sigs/kustomize#539]
Using go version go1.10.4 linux/amd64 on Ubuntu 18.04, the latest master version (5b35443) shows this error when I run it:
```
kustomize flag redefined: log_dir
panic: kustomize flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc4200b6060, 0x134bcc0, 0xc4200c26c0, 0x121504e, 0x7, 0x123f299, 0x2f)
        /usr/lib/go-1.10/src/flag/flag.go:810 +0x540
flag.(*FlagSet).StringVar(0xc4200b6060, 0xc4200c26c0, 0x121504e, 0x7, 0x0, 0x0, 0x123f299, 0x2f)
        /usr/lib/go-1.10/src/flag/flag.go:713 +0x8b
flag.(*FlagSet).String(0xc4200b6060, 0x121504e, 0x7, 0x0, 0x0, 0x123f299, 0x2f, 0xc4200c26b0)
        /usr/lib/go-1.10/src/flag/flag.go:726 +0x8b
flag.String(0x121504e, 0x7, 0x0, 0x0, 0x123f299, 0x2f, 0xc420124000)
        /usr/lib/go-1.10/src/flag/flag.go:733 +0x69
```

Something I did?

**Comment by jcassee** [comment]
Never mind, I got the wrong import path.
