### ISSUE TITLE
kustomize build fails to load CRDs that dont have/need/use metadata.name

### ISSUE THREAD

**Issue by booninite** [kubernetes-sigs/kustomize#641]
I am trying to use `kustomize` with https://github.com/argoproj/argo.

Example spec:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
args: ["hello world"]
```

Argo Workflow CRDs don't require or use `metadata.name`, but I am getting the following error when I try to run `kustomize build` on an Argo Workflow resource:

```
Error: loadResMapFromBasesAndResources: rawResources failed to read Resources: Missing metadata.name in object {map[args:[hello world] kind:Workflow metadata:map[generateName:hello-world-] spec:map[entrypoint:whalesay templates:[map[container:map[command:[cowsay] image:docker/whalesay:latest] name:whalesay]]] apiVersion:argoproj.io/v1alpha1]}
```

Is there a way for me to override where `kustomize` looks for a name to `metadata.generateName`?

**Comment by Liujingfang1** [comment]
Similar issues #627, #586

**Comment by monopole** [comment]
#627 is about names, but currently i see it as a feature request. 

This bug and #586 are noting that kustomize doesn't recognize the kubernetes API directive `generateName` - discussed here: https://kubernetes.io/docs/reference/federation/v1/definitions

This directive is a kustomize-like feature introduced before kustomize... (complicating our life).

We might try to allow it and work with it - or disallow it and provide an alternative mechanism.

**Comment by confiq** [comment]
/remove-lifecycle rotten

I wanted to use generateName with kustomize but I can't :(

**Comment by anarcher** [comment]
I wanted to use generateName with kustomize too.

**Comment by wpbeckwith** [comment]
This issue should be reopened unless it has been solved and the docs don't show it.

**Comment by jarednielsen** [comment]
Agreed, let's re-open and solve the issue.

**Comment by confiq** [comment]
anybody can open with @k8s-ci-robot [robot command](https://github.com/kubernetes-sigs/kustomize/issues/641#issuecomment-504402629). I've already opened, I don't want to flood it :)

**Comment by haimberger** [comment]
/reopen

I've just stumbled across this issue as well, and would appreciate a fix or an alternative mechanism (as mentioned by monopole [above](https://github.com/kubernetes-sigs/kustomize/issues/641#issuecomment-450532493)).

**Comment by Datamance** [comment]
/reopen

sigh.

**Comment by stpierre** [comment]
Can someone with The Power reopen this? Still outstanding AFAICT.

**Comment by stpierre** [comment]
The workaround I've used for Argo specifically is to define my workflow with a `name`:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world-
spec:
  ...
```

And then tell Kustomize to move that to `generateName` as the last patch:

```
resources:
  - hello-world.yaml
patches:
  - patch: |-
      - op: move
        from: /metadata/name
        path: /metadata/generateName
    target:
      kind: Workflow
```

This is obviously not very good, but it does let us use Kustomize with Argo (and without writing a Kustomize plugin).

**Comment by tyuhara** [comment]
I've just faced this issue using [Spinnaker](https://github.com/spinnaker) as well because Spinnaker is updated to [1.20.0](https://www.spinnaker.io/community/releases/versions/1-20-0-changelog) and Kubernetes Job behavior is changed to use `metadata.generateName` filed instead of `metadata.name`.
In this case, kustomize build fails for missing `metadata.name`.

**Comment by posquit0** [comment]
Is there any progress?

**Comment by mgwismer** [comment]
> The workaround I've used for Argo specifically is to define my workflow with a `name`:
> 
> ```
> apiVersion: argoproj.io/v1alpha1
> kind: Workflow
> metadata:
>   name: hello-world-
> spec:
>   ...
> ```
> 
> And then tell Kustomize to move that to `generateName` as the last patch:
> 
> ```
> resources:
>   - hello-world.yaml
> patches:
>   - patch: |-
>       - op: move
>         from: /metadata/name
>         path: /metadata/generateName
>     target:
>       kind: Workflow
> ```
> 
> This is obviously not very good, but it does let us use Kustomize with Argo (and without writing a Kustomize plugin).

But we need to change the generateName to name not the other way around. I tried this but still get the same error, metadata.name missing

**Comment by boonware** [comment]
Is there a progress update on this? It seems like a pretty big limitation. Not being able to us Kustomize with CRDs such as those in Argo Workflows is a huge drawback.

**Comment by boonware** [comment]
The workaround [above](https://github.com/kubernetes-sigs/kustomize/issues/641#issuecomment-617889048) does not work. I am using Kustomize v4.2.0. The following error is thrown. My files are shown below.

```
panic: number of previous names, number of previous namespaces, number of previous kinds not equal

goroutine 1 [running]:
sigs.k8s.io/kustomize/api/resource.(*Resource).PrevIds(...)
	sigs.k8s.io/kustomize/api@v0.8.11/resource/resource.go:345
sigs.k8s.io/kustomize/api/resource.(*Resource).OrgId(0xc0003513b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	sigs.k8s.io/kustomize/api@v0.8.11/resource/resource.go:328 +0x17a
sigs.k8s.io/kustomize/api/builtins.(*PrefixSuffixTransformerPlugin).Transform(0xc002a11d40, 0x4851050, 0xc00000f5f0, 0x0, 0x0)
	sigs.k8s.io/kustomize/api@v0.8.11/builtins/PrefixSuffixTransformer.go:52 +0xa9
sigs.k8s.io/kustomize/api/internal/target.(*multiTransformer).Transform(0xc0000d34e8, 0x4851050, 0xc00000f5f0, 0xc002dabaa0, 0x6)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/target/multitransformer.go:30 +0x79
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/accumulator/resaccumulator.go:142
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).runTransformers(0xc0002f9040, 0xc000366240, 0x0, 0x0)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:270 +0x225
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc0002f9040, 0xc000366240, 0xc00022f610, 0x4449453, 0x0)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:195 +0x2b0
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0xc0002f9040, 0x0, 0xffffffffffffffff, 0x0)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:156 +0xce
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc0002f9040, 0x0, 0x0, 0x0, 0x1)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:111 +0x2f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	sigs.k8s.io/kustomize/api@v0.8.11/internal/target/kusttarget.go:107
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc0000d3d60, 0x484ea60, 0x4c2c0d8, 0x7ffeefbff96f, 0x1f, 0x0, 0x0, 0x0, 0x0)
	sigs.k8s.io/kustomize/api@v0.8.11/krusty/kustomizer.go:88 +0x3dd
sigs.k8s.io/kustomize/kustomize/v4/commands/build.NewCmdBuild.func1(0xc000320580, 0xc00031b500, 0x1, 0x3, 0x0, 0x0)
	sigs.k8s.io/kustomize/kustomize/v4/commands/build/build.go:80 +0x1c9
github.com/spf13/cobra.(*Command).execute(0xc000320580, 0xc00031b4d0, 0x3, 0x3, 0xc000320580, 0xc00031b4d0)
	github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000320000, 0x0, 0xffffffff, 0xc00002e0b8)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	sigs.k8s.io/kustomize/kustomize/v4/main.go:14 +0x2a
```


`cron-workflow.yaml`:
```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: foo
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: main
            templateRef:
              name: main
              template: main
```

`kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
  - cron-workflow.yaml
patches:
  - target:
      kind: CronWorkflow
    path: patch.yaml
```

`patch.yaml`:
```
- op: move
  from: /metadata/name
  path: /metadata/generateName
```

**Comment by RobinNagpal** [comment]
Did anyone find a solution to this? 

```
resources:
  - hello-world.yaml
patches:
  - patch: |-
      - op: move
        from: /metadata/name
        path: /metadata/generateName
    target:
      kind: Workflow
```
used to work for me in `3.8.6` version of kustomize. But stopped working in the latest version i.e. 4.2.0

**Comment by guillaumBrisard** [comment]
Same, the workaround used to work in 3.9.1 and stopped working with the 3.9.4

**Comment by jasonneurohr** [comment]
The workaround worked in 4.3.0 but stopped working for me in 4.4.0.

**Comment by weh** [comment]
> The workaround worked in 4.3.0 but stopped working for me in 4.4.0.

i can confirm this

**Comment by claywd-x** [comment]
Would like to see this fixed as well. Key feature IMO.

**Comment by natasha41575** [comment]
/triage accepted
/kind bug
We will take a closer look to see if we can fix this.

**Comment by fabiohbarbosa** [comment]
Any updates for that?

The patch workaround works neither for `op: move` nor `op: remove`.

```
- op: remove
  path: /metadata/name
```

```
- op: move
  from: /metadata/name
  path: /metadata/generateName
```

**Comment by ricardosferreira** [comment]
I'am also fighting against this issue. it's useful to run a job every time we deploy a new version and we need to generate job names randomly 

this is open a long time ago...
Any deadline?

**Comment by mdrakiburrahman** [comment]
Running into this if a `job` contains `metadata.generateName`, nothing to do with Argo:

```yaml
# kustomization.yaml:
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests.yaml
---
# manifests.yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: upgrade-sql-schema # <---- Problem
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: nginxinc/nginx-unprivileged
          command: ["sleep", "5"]
###
```

Error:
```bash
kubectl kustomize /path/to/folder
error: accumulating resources: accumulation err='accumulating resources from '../../base': '/workspaces/openshift-app-of-apps/sync-waves-demo/kustomize/base' must resolve to a file': recursed accumulation of path '/workspaces/openshift-app-of-apps/sync-waves-demo/kustomize/base': accumulating resources: accumulation err='accumulating resources from 'manifests.yaml': 

missing metadata.name in object {{batch/v1 Job} {{ } map[] map[]}}': got file 'manifests.yaml', but '/workspaces/openshift-app-of-apps/sync-waves-demo/kustomize/base/manifests.yaml' must be a directory to be a root
```

Workaround:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: upgrade-sql-schema # <---- Workaround
...
```

^Kustomize works fine.

Demo is pulled from Argo's [sync-waves](https://github.com/argoproj/argocd-example-apps/blob/master/sync-waves/manifests.yaml) as it depends on `generateName` to run Hook jobs.

**Comment by yanniszark** [comment]
Perhaps a good way for kustomize to deal with `generateName` seemlessly would be to:
1. Detect `generateName` and assign the object a random name with the given `generateName` prefix, but note that it did (for example, it could save some special annotation on the object).
2. Deal with the object as with all others.
3. Before returning the output, do a final pass and remove the name from all resources that have the special annotation set.

This could probably be implemented fairly quickly in code too since it doesn't break kustomize's assumption of identifying objects by apiversion/kind/name/namespace.

**Comment by KnVerey** [comment]
That's definitely an interesting idea. A few complications come to mind: 
1. Resources can be added from several different sources, and each entrypoint would need to handle the conversion (probably doable)
2. Name references can't work with generateName (we don't have the real name, and we can't possibly get it), but with this solution, Kustomize's transformers would do incorrect and potentially confusing things with it. For example, the temporary internal name could show up in object references, or be targeted by replacements.
3. Plugin transformers would be exposed to the workaround, i.e. they would receive objects with both fields populated and need to know what's up with that. In other words, the annotation would need to become part of the KRM Functions standard. I'm very reluctant to do that, since the reason for it is Kustomize internals.

**Comment by dardosordi** [comment]
It appears that the vast majority of us are just trying to generate random names for our jobs. If kustomize just generated the name using generateName as the prefix, most of us will be perfectly happy with it.

**Comment by peteroruba** [comment]
Any chance this gets fixed?

**Comment by luchiniatwork** [comment]
Just ran into this as well when working with Jobs.

**Comment by 24601** [comment]
So our (awkward and somewhat anti-pattern-ish for CI purists, but very acceptable to use and surprisingly not as hack job-ish as I thought it'd be) to be able to run Jobs in Argo with generated names is as follows and is working quite well, actually but is not a "code-based" workaround as much as an alternative way of accomplishing the same thing using different processes:

1. Create a Kustomization that our actual Argo manifests repo uses as a *base* that has *only* the Jobs. For our use case we actually had this Kustomization in turn have its own base it called to do some pre-req stuff the Jobs would need (our jobs do things like reformat/rework secrets in ways Kustomize cannot, prime data stores in ways init containers don't actually work or we don't want to b/c we don't want to have to fork/maintain patches against vendor code, and ensure external resources such as S3 buckets, etc [yes, we have used the ACK S3 controllers, etc, and they are horrible, so we just Job the AWS cli]).
2. This Kustomization uses `namesuffix` for all resources in it, which, of course, is statically configured in the files, but this becomes important in the next step.
3. We have a GitHub Action set up* to detect when this base has changes and when it does not (we use a glob on a specific name we have adopted as a convention for this workaround to check the Git history against the previous commit for the given ref the GH Action is running against to populate this and drive conditionals down the chain as described below).
4. If the changes do *NOT* include a change to the `kustomization.yaml` file that belongs to the base referenced in 1, then it follows the "normal" path of triggering an ArgoCD sync (via webhook). If the changes *DO* include a change to the `customization.yaml` file that belongs to the base referenced in 1, it goes to every occurrence of the base (we have multiple apps that use this pattern now, so it's a for loop with that glob basically) and runs `kustomize edit set namesuffix `head -c 32 /dev/urandom | md5 | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1`-`date +%s`` against each base Kustomization. This is the critical part, because now we can use `namesuffix` as the workaround for the fact `generateName` is inoperable.
5. The GH Action checks these changes back in with a VERY specific commit message (using a PAT, if you use the GH Token given in the Action, the default recursion prevention won't trigger the action and nothing more will happen, e.g. the webhook to ArgoCD is not dispatched given the rule mentioned above on the conditional webhook to avoid unnecessary and/or breaking changes b/c of the Job Immutability issue above, this conditionality ensures only refs with unique Job names are ever sent to ArgoCD for processing/sync).
6. The GH Action is now running again, not against a developer commit/merge, that code path is in GH Action conditions (a bunch of IFs against the changes described above and the absence/presence of the commit message mentioned), but against its own commit (and it checks for this case, too, it also, for safety reasons to avoid recursive GH Actions in an infinite loop until we hit our billing ceiling**). It will then pass the webhook over to ArgoCD for processing now that `namesuffix` is set to something random and unique.

Unsure if this is needed, but we also add the following annotations to all Job manifests:

```
    argocd.argoproj.io/sync-options: Replace=true, Force=true
    argocd.argoproj.io/hook: PostSync, SyncFail
    argocd.argoproj.io/hook-delete-policy: HookFailed, HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
```

*This GH Action has a lot of conditionals and safety checks to avoid loops. Think long and hard about this. You can and will get weirdo edge cases that will cost you a lot of money if you don't! We use self-hosted runners for most stuff, but still, those have to run somewhere...cheaper than GH minutes by far, but still not free. 

**Always a good idea to have a billing ceiling on this stuff, but especially. here IMO. The chance for infinite loops is not nil. Easier to have to go up your low limit every few days than run up a huge bill.

**Comment by lopf** [comment]
We worked around the Job name problem by setting `ttlSecondsAfterFinished: 0` [1] so the Job is removed automatically after completion. The next time the Job is created, the previous one is already deleted.

[1] https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically

**Comment by MeNsaaH** [comment]
Still no work around yet for this. I find myself moving from kustomize to helm charts just because of this 🤦🏿

**Comment by anthonyserious** [comment]
I don't want to get anyone's hopes up, but here's a PR that works in local testing: https://github.com/kubernetes-sigs/kustomize/pull/4981.

I don't understand `kustomize` enough to know if this is really sufficient, but I look forward to comments pointing me in the right direction.

**Comment by hrobertson** [comment]
Looks like [these questions on #4838](https://github.com/kubernetes-sigs/kustomize/pull/4838#issuecomment-1295357914) need answering and comprehensive tests need implementing.

It's not just a case of changing the validation to allow it.

**Comment by anthonyserious** [comment]
Indeed, my PR was too naive there, oh well.  I closed it and hope #4838 moves forward.

**Comment by tmsquill** [comment]
I also have just run into this issue while attempting to use `generateName` on Jobs. Would be nice to see some fix or official workaround communicated.

**Comment by natasha41575** [comment]
I am pasting my comment from https://github.com/kubernetes-sigs/kustomize/pull/4838#issuecomment-1295357914 for visibility:

> I think before we can accept this PR, we need to agree on several details. Again, some more things that come to mind:
> 
> * How `generateName` interacts with namePrefix/nameSuffix. I see above you suggest that `generateName` should not interact with `namePrefix` or `nameSuffix`. That is a valid opinion, and allowing name transformations on `generateName` would complicate name references, but I need to think a bit more about pros/cons.
> * How `generateName` interacts with `patches`? How does a patch target such a resource? For example, some options that I can think of:
>   
>   * Add a new field to the `patch` targets that allow selection based on the `generateName` field.
>   * Keep patch targets as is, and only allow such resources to be targeted by their GVK, labels, and/or annotations.
>   * We will also need to think about if we should allow the patch to change the value of `generateName`. Patches are allowed to change the `name` field, so it may be expected that we eventually support this too.
> * Same as the above, but with `replacements`.
> * What should kustomize do if there are multiple objects with the same `generateName`? Should kustomize allow this, and if so, how can we differentiate between the identical resource IDs? For example, `reswrangler` doesn't let you add two resources with the same ID. I haven't looked carefully at your tests yet, but we should make sure that we have tests covering this.
> * This PR doesn't seem to touch `reswrangler` or `resource` at all. That surprises me, as that is where a lot of resource-identifying code is. Maybe you're right that we actually don't need to touch it at all, but I think it would be helpful to take a closer look at that code and see if it makes sense to add support for `generateName` there.
> 
> I plan to bring this PR up with the other kustomize maintainers but if you have thoughts on these points feel free to share here.
> 
> @KnVerey can you think of anything else we need to make sure we think about?
> 
> Edited to add: I talked with the other maintainers and I think we need to see tests that show the use of `generateName` with all the other generators/transformers fields of kustomize so that we can see how it would behave.

I think to move this issue forward we would need a [mini in-repo KEP](https://github.com/kubernetes-sigs/kustomize/tree/master/proposals#option-2-mini-in-repo-enhancement-proposal) to fully flesh out all of these details.

**Comment by isarns** [comment]
> Any updates for that?
> 
> The patch workaround works neither for `op: move` nor `op: remove`.
> 
> ```
> - op: remove
>   path: /metadata/name
> ```
> 
> ```
> - op: move
>   from: /metadata/name
>   path: /metadata/generateName
> ```

this leads to: 
`panic: number of previous names, number of previous namespaces, number of previous kinds not equal`

**Comment by shuheiktgw** [comment]
Sorry, the issue is a bit too complicated for me. I may come back later, but please take it if anyone else can 🙇 
/unassign

**Comment by kasvith** [comment]
I also ran into same issue with argocd

**Comment by liskl** [comment]
this same issue is happening if you try to customize the knative-operator as it requires a job

**Comment by liskl** [comment]
> How generateName interacts with namePrefix/nameSuffix. I see above you suggest that generateName should not interact with namePrefix or nameSuffix. That is a valid opinion, and allowing name transformations on generateName would complicate name references, but I need to think a bit more about pros/cons.

it should be able to interact with namePrefix
it should not be able to interact with nameSuffix as generateName handles that internally.

but I'm 100% ok with being ignored by both if we can get the functionally working.

> How generateName interacts with patches? How does a patch target such a resource? For example, some options that I can think of:
> 
> Add a new field to the patch targets that allow selection based on the generateName field.
 
This ^

> Keep patch targets as is, and only allow such resources to be targeted by their GVK, labels, and/or annotations.

This is also a valid usecase

```
patches:
  - path: <relative path to file containing patch>
    target:
      group: batch
      version: v1
      kind: Job
      generateName: <the given .metadata.generateName prefix> # only for the kinds that accept them
      namespace: <optional namespace>
      labelSelector: <optional label selector>
      annotationSelector: <optional annotation selector>
```

> We will also need to think about if we should allow the patch to change the value of generateName. Patches are allowed to change the name field, so it may be expected that we eventually support this too.

we should be able to modify the /metadata/generateName field in the same way we could the /metadata/name field using patches

> Same as the above, but with replacements.

we should be able to modify the /metadata/generateName field in the same way we could the /metadata/name field using replacements.


> 
> What should kustomize do if there are multiple objects with the same generateName? Should kustomize allow this, and if so, how can we differentiate between the identical resource IDs? For example, reswrangler doesn't let you add two resources with the same ID. I haven't looked carefully at your tests yet, but we should make sure that we have tests covering this.

kustomize should not allow multiple like-kind resources example `jobs.batch/v1` objects with the same generateName field as that would be abnormal for how the spec is used; the generateName field for the same __Kind__ should be unique within the kustomize output.

> 
> This PR doesn't seem to touch reswrangler or resource at all. That surprises me, as that is where a lot of resource-identifying code is. Maybe you're right that we actually don't need to touch it at all, but I think it would be helpful to take a closer look at that code and see if it makes sense to add support for generateName there.

I don't know enough to state my opinion on this ^

**Comment by markhv-code** [comment]
Also ran into this issue.

**Comment by ricardo-s-ferreira-alb** [comment]
> Also ran into this issue.

And 5 years later we have no solution.

**Comment by ashrafguitoni** [comment]
Not sure what's the best way to get developer's attention to this... Maybe opening a discussion? Is there an official slack?

**Comment by nicl-dev** [comment]
We also just ran into this. What exactly can we do to bring this forward? All related PR's got closed so what's the plan now?

**Comment by mcharb** [comment]
I'm working on a project where Kustomize was selected for ArgoCD.  We were hoping to extend its use to our Argo Workflows but this is a significant impediment.  Deleting previous workflow instances as was suggested in one comment does not align with our operational requirements.  I'm sure there are usecases outside of Argo Workflow that are also affected by this issue.

**Comment by robinhuiser** [comment]
Please provide a solution or how we can support the kustomize team closing this issue - it is blocking our pipeline development in Argo Workflow at this moment as we want to kustomize pipelines.

**Comment by tkblack** [comment]
I ran into this. I want found the solution but failed. I tried like below and be OK! 
```
patches: 
- patch: | 
    - op: replace
      path: /metadata
      value: 
        generateName: data-migration-
  target: 
    kind: Job
```

**Comment by tkblack** [comment]
> I ran into this. I want found the solution but failed. I tried like below and be OK!
> 
> ```
> patches: 
> - patch: | 
>     - op: replace
>       path: /metadata
>       value: 
>         generateName: data-migration-
>   target: 
>     kind: Job
> ```

Oh. No, it just ok for `kubectl kustomize`, but failed with argocd. And, i run with `kustomize build` would be failed too. 
kustomize version: v4.4.0

**Comment by bluebrown** [comment]
> > I ran into this. I want found the solution but failed. I tried like below and be OK!
> > ```
> > patches: 
> > - patch: | 
> >     - op: replace
> >       path: /metadata
> >       value: 
> >         generateName: data-migration-
> >   target: 
> >     kind: Job
> > ```
> 
> Oh. No, it just ok for `kubectl kustomize`, but failed with argocd. And, i run with `kustomize build` would be failed too. kustomize version: v4.4.0

Kubectl kustomize is literally kustomize. And the one in argocd as well. There is no difference, except for the version that is used.

**Comment by natasha41575** [comment]
Repeating what I wrote in https://github.com/kubernetes-sigs/kustomize/issues/641#issuecomment-1684304344:

To move this issue forward we would need a [mini in-repo KEP](https://github.com/kubernetes-sigs/kustomize/tree/master/proposals#option-2-mini-in-repo-enhancement-proposal) to fully flesh out all the design and implementation details of how this feature would be handled.

**Comment by sanmai-NL** [comment]
The interesting part is, who writes that proposal. And why would, for example, the community write this one and the maintainers some other?

**Comment by shadiramadan** [comment]
For people looking for a solution- this utilizes an exec krm plugin.
It depends on yq and openssl rand.

Folder structure
```
base/
  job-name-generator.yaml
  job.yaml
  kustomization.yaml
plugins/
  job-name-generator.sh
```

`kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
# The job is added by the generator
# - job.yaml
generators:
- job-name-generator.yaml
```

`job.yaml`
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: schema-migrate-
spec:
  template:
    spec: {}
```

`job-name-generator.yaml`
```yaml
apiVersion: my-app-version/v1
kind: JobNameGenerator
metadata:
  name: schema-migrate
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ../plugins/job-name-generator.sh
spec:
  resourcePath: ./job.yaml
```

`job-name-generator.sh`
```shell
#!/usr/bin/env bash

# read the `kind: ResourceList` from stdin
resourceList=$(cat)

# extract the resource path
export resourcePath=$(echo "${resourceList}" | yq e '.functionConfig.spec.resourcePath' - )

# generate the job hash
export job_hash=$(openssl rand -hex 3 | cut -c 1-5)

# dump the job into the output ResourceList, add name from generateName + the job hash, and delete generateName
echo "
kind: ResourceList
items: []
" | yq e 'load(env(resourcePath)) as $resource | .items += $resource | .items[0].metadata.name = .items[0].metadata.generateName + env(job_hash) | del(.items[0].metadata.generateName)' -
```

**Comment by montanaflynn** [comment]
I need this for jobs, otherwise I get immutable errors everytime I run kustomize unless deleting the previous job first.

```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: migrate-schem-
```

**Comment by ricardo-s-ferreira-alb** [comment]
> I need this for jobs, otherwise I get immutable errors everytime I run kustomize unless deleting the previous job first.
> 
> ```
> apiVersion: batch/v1
> kind: Job
> metadata:
>   generateName: migrate-schem-
> ```

I've fixed this by setting a short ttl and verifiy the job can run multi times.

**Comment by zakariaanzid** [comment]
Is there still no solution for this ? 
I faced this issue with argocd, as i was trying to re-deploy the same job automatically each time, what i did as a solution was to add an argocd presync hook with deletion after success, as a job, but even that one can't be re-deployed unless there was a change on its manifets. generateName still isn't working with kustomize.
Anyone has any bright idea guys ?

**Comment by Sturgelose** [comment]
It is still a bit WIP, but this seems to do the trick https://github.com/Sturgelose/kustomize-job-hasher

I've packed a transformer to update the job's name in a container, using Kustomize fn.

I might add proper versioning and argocd examples in the future, but it should be already usable.

**Comment by Preisschild** [comment]
fyi instead of using generateName you can annotate the resource with `internal.config.kubernetes.io/needsHashSuffix: "enabled"` and it adds the hash of all fields as suffix to the resource name. You can reference those via namereference then.
