### ISSUE TITLE
panic: kustomize flag redefined: log_dir

### ISSUE THREAD

**Issue by leominov** [kubernetes-sigs/kustomize#648]
Just moved `kustomize_1.0.11_darwin_amd64` to `/usr/local/bin/kustomize` and got this:

```
$ kustomize version
kustomize flag redefined: log_dir
panic: kustomize flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000ac180, 0x1fc77c0, 0xc00003a8d0, 0x1e39f7f, 0x7, 0x1e641ef, 0x2f)
	/usr/local/Cellar/go/1.11/libexec/src/flag/flag.go:805 +0x529
flag.(*FlagSet).StringVar(0xc0000ac180, 0xc00003a8d0, 0x1e39f7f, 0x7, 0x0, 0x0, 0x1e641ef, 0x2f)
	/usr/local/Cellar/go/1.11/libexec/src/flag/flag.go:708 +0x8a
flag.(*FlagSet).String(0xc0000ac180, 0x1e39f7f, 0x7, 0x0, 0x0, 0x1e641ef, 0x2f, 0xc00003a8c0)
	/usr/local/Cellar/go/1.11/libexec/src/flag/flag.go:721 +0x8b
flag.String(0x1e39f7f, 0x7, 0x0, 0x0, 0x1e641ef, 0x2f, 0xc0000efe01)
	/usr/local/Cellar/go/1.11/libexec/src/flag/flag.go:728 +0x69
```

but:

```
$ /usr/local/bin/kustomize version
Version: {KustomizeVersion:1.0.11 GitCommit:8f701a00417a812558a7b785e8354957afa469ae BuildDate:2018-12-04T18:42:24Z GoOs:unknown GoArch:unknown}
```

Sounds like #539 but I download binary from Releases tab.

**Comment by leominov** [comment]
And why `GoOs:unknown` and `GoArch:unknown`? :)

**Comment by leominov** [comment]
My bad

**Comment by leominov** [comment]
If you googled this issue here is the key – remove all copies of binary from your PATH and install again.
